# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-gke-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      role: frontend
      env: canary
  template:
    metadata:
      labels:
        app: hello
        role: frontend
        env: canary
    spec:
      containers:
      - name: hello-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/$GCLOUD_PROJECT/test2:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
